version: '3'
services:
  postgres:
    build: /
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"

volumes:
  db-data: